Cycle api/content/worker deployments on upgrade
When upgrading with an old pulpcore version (like 3.49) to a newer
one (like 3.73) then we need to scale down the api, conten and
worker deployments before doing the database migration.

In the past, we already did the some regarding the pulp_ansible version
so this is just doing the same when pulpcore is lower than 3.50

RuntimeError: Incompatible versions detected (core >= 3.50.0 needed):
  - 'core'='3.49.56' with api server '3@automation-hub-api-6754f5586b-vm42g'
  - 'core'='3.49.56' with api server '2@automation-hub-api-6754f5586b-vm42g'
  - 'core'='3.49.56' with content server '6@automation-hub-content-67bbbc4f56-z868x'
  - 'core'='3.49.56' with content server '8@automation-hub-content-67bbbc4f56-z868x'
  - 'core'='3.49.56' with pulp worker '1@automation-hub-worker-6457b678c-kl772'
  - 'core'='3.49.56' with pulp worker '1@automation-hub-worker-6457b678c-t79n2'
Please shutdown or upgrade the outdated components before you continue the migration.
If the components were not gracefully shutdown, wait for the larger component TTL period before running the migration
(API_APP_TTL, CONTENT_APP_TTL or WORKER_TTL).

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>